import type { OxlintConfig } from "oxlint"

type RuleConfig = NonNullable<OxlintConfig["rules"]>

const rules: RuleConfig = {
  "node/no-top-level-await": "off",
  "unicorn/max-nested-calls": "off",
  "typescript/prefer-readonly-parameter-types": "off",
  "typescript/explicit-function-return-type": "off",
  "typescript/explicit-module-boundary-types": "off",
  "unicorn/prefer-global-this": "off",
  "func-style": ["error", "expression"],
  "no-magic-numbers": "off",
  "oxc/no-optional-chaining": "off",
  "oxc/no-rest-spread-properties": "off",
  "oxc/no-async-await": "off",
  "unicorn/no-null": "off",
  "sort-imports": "off",
  "no-undefined": "off",
  "max-statements": "off",
  "unicorn/no-process-exit": "off",
  "no-ternary": "off",
  "no-continue": "off",
  "prefer-destructuring": "off",
  "no-console": "off",
  "no-warning-comments": "off",
  "max-params": "off",
  "max-lines-per-function": "off",
  "id-length": "off",
  "no-inline-comments": "off",
  "unicorn/no-array-reduce": "error",
  "no-use-before-define": "error",
  "node/callback-return": "off",
  "no-duplicate-imports": "off",
  "no-void": "off",
  "typescript/explicit-member-accessibility": "off",
  complexity: "error",
  "max-classes-per-file": "off",
  "require-await": "off",
  "no-plusplus": "error",
  "init-declarations": "error",
  "sort-keys": "off",
  "oxc/erasing-op": "error",
  "no-nested-ternary": "off",
  "unicorn/no-nested-ternary": "off",
  "typescript/use-unknown-in-catch-callback-variable": "error",
  "typescript/no-non-null-assertion": "error",
  "oxc/no-map-spread": "off",
  "unicorn/no-await-expression-member": "error",
  "no-empty-function": "error",
  "unicorn/no-useless-collection-argument": "error",
  "unicorn/prefer-ternary": "error",
  "no-negated-condition": "error",
  "typescript/array-type": "error",
  "arrow-body-style": ["error", "as-needed", { requireReturnForObjectLiteral: true }],
  "import/prefer-default-export": "off",
  "import/no-namespace": "off",
  "import/no-named-export": "off",
  "promise/prefer-await-to-then": "error",
  "import/group-exports": "error",
  "promise/prefer-await-to-callbacks": "off",
  "node/no-process-env": "error",
  "import/exports-last": "error",
  "import/max-dependencies": "off",
  "import/consistent-type-specifier-style": ["error", "prefer-top-level"],
  "typescript/no-import-type-side-effects": "error",
  "import/no-relative-parent-imports": "error",
  "oxc/no-barrel-file": "error",
  "import/first": "error",
  "promise/avoid-new": "error",
  "import/no-nodejs-modules": "off",
  "import/no-default-export": "error",
  "no-underscore-dangle": ["error", { allow: ["__dirname", "__filename"] }],
  "react/react-compiler": "error",
  "react/jsx-no-literals": "off",
  "react/react-in-jsx-scope": "off",
  "react/jsx-filename-extension": "off",
  "react-perf/jsx-no-new-function-as-prop": "off",
  "react/jsx-max-depth": "off",
  "react-perf/jsx-no-new-array-as-prop": "off",
  "react-perf/jsx-no-new-object-as-prop": "error",
  "react/no-children-prop": "error",
  "react-perf/jsx-no-jsx-as-prop": "off",
  "react/jsx-handler-names": "off",
  "react/only-export-components": "off",
  "react/jsx-props-no-spreading": "off",
  "react/no-multi-comp": "off",
  "react/hook-use-state": "off",
  "react/forbid-component-props": "off",
  "react/function-component-definition": "off",
}

export { rules }
